version: "3.9"

services:
  test:
    build:
      context: ./src/test
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src/test:/app
    environment:
      - NGINX_PORT=80
  test-accessible:
    build:
      context: ./src/test-accessible
      dockerfile: Dockerfile
    ports:
      - "8181:80"
    volumes:
      - ./src/test:/app
    environment:
      - NGINX_PORT=80
  navigator:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"